const SUPABASE_URL = "https://bevihbuyushkdtrkeoil.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJldmloYnV5dXNoa2R0cmtlb2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEzMzExNDksImV4cCI6MjEwNjkwNzE0OX0.0TdeD9GP8K4TSzCheLb_JJApjO3dsdTnac-7JIr3o1Y";


const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
